'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const I18N_DIR = path.join(ROOT, 'src/i18n');
const OUT_FILE = path.join(ROOT, 'src/js/i18n-data.js');
const SCAN_DIRS = [
	path.join(ROOT, 'src/js'),
	path.join(ROOT, 'src'),
];
const SCAN_EXT = new Set(['.js', '.html']);

const LOCALE_LABELS = {
	en: 'English',
	ru: 'Русский',
	it: 'Italiano',
	es: 'Español',
	pt: 'Português',
	pl: 'Polski',
};

function walkFiles(dir, out) {
	if (!fs.existsSync(dir)) return;
	for (const name of fs.readdirSync(dir)) {
		const full = path.join(dir, name);
		const stat = fs.statSync(full);
		if (stat.isDirectory()) {
			if (name === 'node_modules' || name === 'i18n') continue;
			walkFiles(full, out);
			continue;
		}
		if (SCAN_EXT.has(path.extname(name))) out.push(full);
	}
}

function collectKeys(files) {
	const keys = new Set();
	const patterns = [
		/\bt\(\s*['"]([^'"]+)['"]/g,
		/setAuthState\(\s*[^,]+,\s*['"]([^'"]+)['"]/g,
		/data-i18n="([^"]+)"/g,
		/data-i18n-placeholder="([^"]+)"/g,
		/data-i18n-title="([^"]+)"/g,
		/data-i18n-alt="([^"]+)"/g,
	];
	for (const file of files) {
		if (file.endsWith('i18n-data.js')) continue;
		const text = fs.readFileSync(file, 'utf8');
		for (const re of patterns) {
			re.lastIndex = 0;
			let m;
			while ((m = re.exec(text))) keys.add(m[1]);
		}
	}
	return keys;
}

function loadLocales() {
	const locales = {};
	for (const file of fs.readdirSync(I18N_DIR)) {
		if (!file.endsWith('.json')) continue;
		const code = path.basename(file, '.json');
		locales[code] = JSON.parse(fs.readFileSync(path.join(I18N_DIR, file), 'utf8'));
	}
	return locales;
}

function pickMessages(locales, keys) {
	const out = {};
	for (const [locale, bag] of Object.entries(locales)) {
		out[locale] = {};
		for (const key of keys) {
			if (bag[key] != null) out[locale][key] = bag[key];
			else if (locale !== 'en' && locales.en[key] != null) {
				console.warn(`[i18n] missing ${locale}.${key}, falling back to en`);
				out[locale][key] = locales.en[key];
			}
		}
	}
	return out;
}

function emit(messages) {
	const body = JSON.stringify(messages, null, '\t');
	const labels = JSON.stringify(LOCALE_LABELS, null, '\t');
	return `// AUTO-GENERATED by scripts/build-i18n.js — do not edit
export const MESSAGES = ${body};
export const DEFAULT_LOCALE = 'en';
export const LOCALE_LABELS = ${labels};
`;
}

function main() {
	const files = [];
	for (const dir of SCAN_DIRS) walkFiles(dir, files);
	const keys = collectKeys(files);
	if (!keys.size) {
		console.error('[i18n] no keys found');
		process.exit(1);
	}
	const locales = loadLocales();
	if (!locales.en) {
		console.error('[i18n] src/i18n/en.json is required');
		process.exit(1);
	}
	for (const key of keys) {
		if (locales.en[key] == null) {
			console.warn(`[i18n] key "${key}" used in code but missing from en.json`);
		}
	}
	const messages = pickMessages(locales, keys);
	fs.writeFileSync(OUT_FILE, emit(messages), 'utf8');
	console.log(`[i18n] wrote ${OUT_FILE} (${keys.size} keys, ${Object.keys(messages).length} locales)`);
}

main();
